server:
  port: 8010
spring:
  application:
    name: microserver-simple-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://aojie:caj123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true