spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccms_elancy
    username: root
    password: 123456

    logging:
        file:   /logs # 日志文件,绝对路径或相对路径
        path:   d: # 保存日志文件目录路径
        config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
        level:  INFO # 日志级别
            org.springframework.web: DEBUG # 配置spring web日志级别